name: Build and publish Docker image

on:
  push:
    tags: 
      - 'v*'

jobs: 
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/Checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login in Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dns-checker:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/dns-checker:latest

      - name: Display result
        run: |
          echo "[-] Imagen publicada:"
          echo "  - ${{ secrets.DOCKERHUB_USERNAME }}/dns-checker:${{ env.VERSION }}"
          echo "  - ${{ secrets.DOCKERHUB_USERNAME }}/dns-checker:latest"